{
 "title": "TAPIS Reporting",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "repo", "query": { "query": "" } },
   { "name": "auth_dbs", "query": "show databases;" }
  ]
 },
 "panels": [
  { "title": "API Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Tenants",
   "type": "stat",
   "description": "https://admin.develop.tapis.io/v3/tenants",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "source": "url",
     "type": "json",
     "url": "https://admin.develop.tapis.io/v3/tenants",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Top 10 API Requests by Tenant",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: tapis-nginx AND NOT tapis_path : \"healthcheck\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Daily API Requests by Tenant (excl. health check)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: tapis-nginx AND NOT tapis_path : \"healthcheck\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: tapis-nginx AND NOT tapis_path : \"healthcheck\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Number of jobs using smart scheduling",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  created as \"time\", 1 as \"metric\"\nFROM jobs\nWHERE\n  $__timeFilter(created)\n  AND dynamic_exec_system = true"
    }
   ]
  },
  {
   "title": "Number of jobs created per day ",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(created,'24h',0)*1000 AS \"date_created\"\nFROM\n  jobs\nWHERE\n  $__timeFilter(created)\n  "
    }
   ]
  },
  {
   "title": "Average number of jobs created per day ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(jobsByDay.count)\nFROM (SELECT created::date AS day, count(*) FROM jobs GROUP BY day) jobsByDay\nWHERE\n  $__timeFilter(day)"
    }
   ]
  },
  { "title": "Apps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Number of Applications",
   "type": "stat",
   "description": "Number of containerized applications registered",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(seq_id) from tapis_app.apps where deleted = false;"
    }
   ]
  },
  {
   "title": "Apps Requests by Tenant (excluding health check)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: tapis-nginx NOT tapis_path : \"healthcheck\" AND tapis_service: \"apps\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Streams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Number of Streams by Type",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tapis_streams_transfers_total", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Streams Transferred Data Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tapis_streams_transfers_bytes_total",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Github Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "${repo}",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 37 },
   "repeat": "repo",
   "targets": [
    {
     "alias": "Random Walk",
     "dataOverrides": [
      {
       "operator": ">=",
       "override": "null",
       "values": [
        "${__value.index}",
        "10"
       ]
      }
     ],
     "expression": "                                             ",
     "parser": "backend",
     "source": "url",
     "summarizeBy": "state",
     "summarizeExpression": "count(title)",
     "type": "json",
     "uql": "parse-json",
     "url": "https://api.github.com/repos/tapis-project/${repo}/issues?state=all&filter=all",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": []
     }
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Number of Gateways",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "source": "url",
     "type": "json",
     "url": "https://raw.githubusercontent.com/tapis-project/tapis-reporting/main/tapis_gateways.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Total Number of Training Attendees",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "source": "url",
     "type": "json",
     "url": "https://raw.githubusercontent.com/tapis-project/tapis-reporting/main/tapis_training.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Total Number of v2 Access Tokens for $auth_dbs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 53 },
   "repeat": "auth_dbs",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct AUTHZ_USER) from `apimgtdb_${auth_dbs:raw}`.IDN_OAUTH2_ACCESS_TOKEN;"
    }
   ]
  }
 ]
}